name: GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List open pull requests
        run: hub pr list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
