#!/usr/bin/env bash
set -e

STATUS=0

{ /opt/hostedtoolcache/Ruby/3.0/x64/bin/ruby --version
  /opt/hostedtoolcache/Ruby/3.0/x64/bin/bundle install
  bundle binstub cucumber --path bin
} || {
  echo "You need Ruby 1.9 or higher and Bundler to run hub tests" >&2
  STATUS=1
}

if [ $STATUS -eq 0 ]; then
  echo "Everything OK."
fi

exit $STATUS
