name: Release
on:
  push:
    tags: "v*"

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.18"

      - name: Publish release script
        run: script/publish-release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Fork repository
        run: script/fork-repository.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: "!contains(github.ref, '-')" # skip prereleases
    - uses: mislav/bump-homebrew-formula-action@v4
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: hub
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
